"""命令列（install / uninstall / doctor …）的訊息，併進 i18n 的字串表，語言跟著 config.json 的 lang。"""

EN = {
    "cli.desc": "Claude Pet: a hand-drawn desktop pet that follows what Claude Code is doing (Windows).",
    "cli.windows_only": "Claude Pet only runs on Windows.",
    "cli.started": "Started the pet.",
    "cli.already_running": "The pet is already running.",
    "cli.stopped": "Asked the pet to quit.",
    "cli.not_running": "The pet isn't running.",
    "cli.dry_run": "[dry run] nothing was changed.",

    "install.settings_error": "Couldn't read {path}: {err}",
    "install.settings_error_hint": "Nothing was changed. Fix or remove that file, then run again.",
    "install.not_importable": "Python at {py} can't import claude_pet from other folders, so the hooks would fail.",
    "install.not_importable_hint": "Running from a source checkout? Run 'pip install -e .' first, then try again.",
    "install.hooks_done": "Hooks installed in {path} ({n} events).",
    "install.hooks_replaced": "Replaced {n} older claude-pet hook entries.",
    "install.hooks_same": "Hooks in {path} are already up to date.",
    "install.backup": "Backup of your settings: {path}",
    "install.space_warning": "Note: Python's path contains spaces and there is no short path, so the hook command uses PowerShell syntax.",
    "install.shortcut": "Desktop shortcut: {path}",
    "install.shortcut_old_removed": "Removed an old shortcut that pointed at pet.py: {path}",
    "install.shortcut_failed": "Couldn't create the desktop shortcut: {err}",
    "install.done": "Done. Open a new Claude Code session (or restart the current one) so the hooks take effect.",

    "uninstall.hooks_removed": "Removed {n} hook entries from {path}.",
    "uninstall.no_hooks": "No claude-pet hooks found in {path}.",
    "uninstall.shortcut_removed": "Removed shortcut: {path}",
    "uninstall.stopped": "Stopped the running pet.",
    "uninstall.purged": "Deleted {path}.",
    "uninstall.kept": "Your settings and cache in {path} were kept (add --purge to delete them).",
    "uninstall.next": "Last step: pip uninstall claude-pet   (or: pipx uninstall claude-pet)",

    "doctor.title": "Claude Pet doctor",
    "doctor.windows": "Windows",
    "doctor.python": "Python",
    "doctor.tk": "tkinter",
    "doctor.pillow": "Pillow",
    "doctor.fonts": "Fonts",
    "doctor.fonts_missing": "missing: {names} (text may look different)",
    "doctor.claude": "claude command",
    "doctor.claude_missing": "not found. Install Claude Code, or set claude_path in {path}",
    "doctor.importable": "Importable by hooks",
    "doctor.importable_no": "no. Run 'pip install -e .' (source checkout) or reinstall the package",
    "doctor.hooks": "Claude Code hooks",
    "doctor.hooks_ok": "{n}/{total} events set up in {path}",
    "doctor.hooks_none": "not installed. Run: claude-pet install",
    "doctor.hooks_partial": "{n}/{total} events set up. Run: claude-pet install",
    "doctor.hooks_legacy": "old-style entries found. Run: claude-pet install (it replaces them)",
    "doctor.settings_bad": "can't read {path}: {err}",
    "doctor.running": "Pet process",
    "doctor.running_yes": "running",
    "doctor.running_no": "not running (it starts automatically when Claude Code starts working, or run: claude-pet)",
    "doctor.data": "Data folder",
    "doctor.all_ok": "All good.",
    "doctor.problems": "{n} problem(s) found.",
}

ZH = {
    "cli.desc": "Claude 小克：會跟著 Claude Code 動作的手繪風桌面寵物（Windows）。",
    "cli.windows_only": "Claude 小克只能在 Windows 上執行。",
    "cli.started": "已啟動小克。",
    "cli.already_running": "小克已經在跑了。",
    "cli.stopped": "已請小克結束。",
    "cli.not_running": "小克目前沒有在跑。",
    "cli.dry_run": "[試跑] 沒有改動任何東西。",

    "install.settings_error": "讀不了 {path}：{err}",
    "install.settings_error_hint": "沒有做任何改動。請修好或移除那個檔案後再執行一次。",
    "install.not_importable": "{py} 在其他資料夾底下 import 不到 claude_pet，hooks 會失敗。",
    "install.not_importable_hint": "如果你是從原始碼資料夾執行，請先執行 'pip install -e .' 再試一次。",
    "install.hooks_done": "已在 {path} 設定好 hooks（{n} 個事件）。",
    "install.hooks_replaced": "取代了 {n} 筆舊的 claude-pet hook。",
    "install.hooks_same": "{path} 裡的 hooks 已經是最新的。",
    "install.backup": "已備份你原本的設定：{path}",
    "install.space_warning": "注意：Python 的路徑含有空白又沒有短路徑可用，所以 hook 指令用了 PowerShell 的寫法。",
    "install.shortcut": "桌面捷徑：{path}",
    "install.shortcut_old_removed": "已移除指向 pet.py 的舊捷徑：{path}",
    "install.shortcut_failed": "建立桌面捷徑失敗：{err}",
    "install.done": "完成。請開一個新的 Claude Code 對話（或重啟目前的），hooks 才會生效。",

    "uninstall.hooks_removed": "已從 {path} 移除 {n} 筆 hook。",
    "uninstall.no_hooks": "{path} 裡沒有找到 claude-pet 的 hooks。",
    "uninstall.shortcut_removed": "已移除捷徑：{path}",
    "uninstall.stopped": "已結束執行中的小克。",
    "uninstall.purged": "已刪除 {path}。",
    "uninstall.kept": "{path} 裡的設定與快取保留著（加上 --purge 可以一併刪除）。",
    "uninstall.next": "最後一步：pip uninstall claude-pet   （用 pipx 裝的就是 pipx uninstall claude-pet）",

    "doctor.title": "Claude 小克 診斷",
    "doctor.windows": "Windows",
    "doctor.python": "Python",
    "doctor.tk": "tkinter",
    "doctor.pillow": "Pillow",
    "doctor.fonts": "字型",
    "doctor.fonts_missing": "缺少：{names}（文字外觀可能不同）",
    "doctor.claude": "claude 指令",
    "doctor.claude_missing": "找不到。請安裝 Claude Code，或在 {path} 設定 claude_path",
    "doctor.importable": "hooks 能載入套件",
    "doctor.importable_no": "不行。請執行 'pip install -e .'（原始碼資料夾）或重新安裝套件",
    "doctor.hooks": "Claude Code hooks",
    "doctor.hooks_ok": "{path} 已設定 {n}/{total} 個事件",
    "doctor.hooks_none": "還沒安裝。請執行：claude-pet install",
    "doctor.hooks_partial": "只設定了 {n}/{total} 個事件。請執行：claude-pet install",
    "doctor.hooks_legacy": "發現舊式的設定。請執行：claude-pet install（會自動取代）",
    "doctor.settings_bad": "讀不了 {path}：{err}",
    "doctor.running": "小克行程",
    "doctor.running_yes": "執行中",
    "doctor.running_no": "沒有在跑（Claude Code 開始工作時會自動叫出，或執行：claude-pet）",
    "doctor.data": "資料夾",
    "doctor.all_ok": "一切正常。",
    "doctor.problems": "發現 {n} 個問題。",
}


ZH_CN = {
    "cli.desc": "Claude 小克：会跟着 Claude Code 动作的手绘风桌面宠物（Windows）。",
    "cli.windows_only": "Claude 小克只能在 Windows 上运行。",
    "cli.started": "已启动小克。",
    "cli.already_running": "小克已经在运行了。",
    "cli.stopped": "已请小克退出。",
    "cli.not_running": "小克当前没有在运行。",
    "cli.dry_run": "[试运行] 没有改动任何内容。",

    "install.settings_error": "无法读取 {path}：{err}",
    "install.settings_error_hint": "没有做任何改动。请修好或移除该文件后再运行一次。",
    "install.not_importable": "{py} 在其他文件夹下无法 import claude_pet，hooks 会失败。",
    "install.not_importable_hint": "如果你是从源码文件夹运行的，请先执行 'pip install -e .' 再试一次。",
    "install.hooks_done": "已在 {path} 中配置好 hooks（{n} 个事件）。",
    "install.hooks_replaced": "替换了 {n} 条旧的 claude-pet hook。",
    "install.hooks_same": "{path} 中的 hooks 已经是最新的。",
    "install.backup": "已备份你原有的设置：{path}",
    "install.space_warning": "注意：Python 的路径含有空格，又没有可用的短路径，所以 hook 命令使用了 PowerShell 的写法。",
    "install.shortcut": "桌面快捷方式：{path}",
    "install.shortcut_old_removed": "已移除指向 pet.py 的旧快捷方式：{path}",
    "install.shortcut_failed": "创建桌面快捷方式失败：{err}",
    "install.done": "完成。请新开一个 Claude Code 对话（或重启当前对话），hooks 才会生效。",

    "uninstall.hooks_removed": "已从 {path} 中移除 {n} 条 hook。",
    "uninstall.no_hooks": "{path} 中没有找到 claude-pet 的 hooks。",
    "uninstall.shortcut_removed": "已移除快捷方式：{path}",
    "uninstall.stopped": "已关闭正在运行的小克。",
    "uninstall.purged": "已删除 {path}。",
    "uninstall.kept": "{path} 中的设置和缓存已保留（加上 --purge 可一并删除）。",
    "uninstall.next": "最后一步：pip uninstall claude-pet   （用 pipx 安装的则是 pipx uninstall claude-pet）",

    "doctor.title": "Claude 小克 诊断",
    "doctor.windows": "Windows",
    "doctor.python": "Python",
    "doctor.tk": "tkinter",
    "doctor.pillow": "Pillow",
    "doctor.fonts": "字体",
    "doctor.fonts_missing": "缺少：{names}（文字外观可能不同）",
    "doctor.claude": "claude 命令",
    "doctor.claude_missing": "找不到。请安装 Claude Code，或在 {path} 中设置 claude_path",
    "doctor.importable": "hooks 能加载包",
    "doctor.importable_no": "不能。请执行 'pip install -e .'（源码文件夹）或重新安装该包",
    "doctor.hooks": "Claude Code hooks",
    "doctor.hooks_ok": "{path} 中已配置 {n}/{total} 个事件",
    "doctor.hooks_none": "尚未安装。请执行：claude-pet install",
    "doctor.hooks_partial": "只配置了 {n}/{total} 个事件。请执行：claude-pet install",
    "doctor.hooks_legacy": "发现旧式配置。请执行：claude-pet install（会自动替换）",
    "doctor.settings_bad": "无法读取 {path}：{err}",
    "doctor.running": "小克进程",
    "doctor.running_yes": "运行中",
    "doctor.running_no": "没有在运行（Claude Code 开始工作时会自动叫出，或执行：claude-pet）",
    "doctor.data": "数据文件夹",
    "doctor.all_ok": "一切正常。",
    "doctor.problems": "发现 {n} 个问题。",
}

# 更新功能（介面與命令列）的字串；i18n.py 會把它們併進同一張表
EN.update({
    'menu.update': 'Update to v{version}',
    'bubble.update': 'Update available: v{version}',
    'bubble.updated': 'Updated to v{version}!',
    'bubble.update_failed': 'Update failed. See update.log',
    'bubble.up_to_date': "You're up to date (v{version})",
    'bubble.update_checking': 'Checking for updates…',
    'bubble.update_error': "Couldn't check for updates",
    'bubble.update_unconfigured': "Updates aren't set up yet",
    'settings.updates': 'Updates',
    'settings.updates_desc': 'Check GitHub once a day and remind me when a new version is out',
    'settings.check_now': 'Check now',
    'update.status.latest': 'Version {version} · up to date',
    'update.status.available': 'Version {current} · v{latest} is available',
    'update.status.checking': 'Checking…',
    'update.status.error': "Version {version} · couldn't check right now",
    'update.status.unconfigured': "Version {version} · update checking isn't set up yet",
    'update.title': 'Update available',
    'update.subtitle': 'v{current} → v{latest}',
    'update.whats_new': "What's new",
    'update.no_notes': '(No release notes provided.)',
    'update.now': 'Update now',
    'update.later': 'Later',
    'update.skip': 'Skip this version',
    'update.updating': 'Updating… the pet will quit and come back in a moment.',
    'update.dev': "This is a source checkout, so it won't update itself. Run 'git pull' in its folder.",
    'update.cli.unconfigured': "Update checking isn't set up yet (the GitHub repository hasn't been configured).",
    'update.cli.latest': "You're on the latest version (v{version}).",
    'update.cli.available': 'A new version is available: v{latest} (you have v{current}).',
    'update.cli.notes': "What's new:",
    'update.cli.error': "Couldn't check for updates: {err}",
    'update.cli.confirm': 'Update now? [y/N] ',
    'update.cli.cancelled': 'Not updating.',
    'update.cli.started': "Updating in the background. The pet will restart when it's done. Log: {path}",
    'update.cli.dev': "This is a source checkout; update it with 'git pull' instead.",
    'update.cli.hint': "Run 'claude-pet update' to install it.",
})
ZH.update({
    'menu.update': '更新到 v{version}',
    'bubble.update': '有新版本：v{version}',
    'bubble.updated': '已更新到 v{version}！',
    'bubble.update_failed': '更新失敗，請看 update.log',
    'bubble.up_to_date': '已經是最新版（v{version}）',
    'bubble.update_checking': '檢查更新中…',
    'bubble.update_error': '檢查不了更新',
    'bubble.update_unconfigured': '還沒有設定更新來源',
    'settings.updates': '更新',
    'settings.updates_desc': '每天檢查一次 GitHub，有新版本時提醒我',
    'settings.check_now': '立即檢查',
    'update.status.latest': '版本 {version}・已是最新',
    'update.status.available': '版本 {current}・有新版 v{latest}',
    'update.status.checking': '檢查中…',
    'update.status.error': '版本 {version}・目前檢查不了',
    'update.status.unconfigured': '版本 {version}・還沒有設定更新來源',
    'update.title': '有新版本',
    'update.subtitle': 'v{current} → v{latest}',
    'update.whats_new': '更新內容',
    'update.no_notes': '（沒有提供更新說明）',
    'update.now': '立即更新',
    'update.later': '稍後再說',
    'update.skip': '跳過這個版本',
    'update.updating': '更新中…小克會先關掉，馬上回來。',
    'update.dev': "這是原始碼資料夾，不會自己更新。請在資料夾裡執行 'git pull'。",
    'update.cli.unconfigured': '還沒有設定更新來源（尚未指定 GitHub 庫）。',
    'update.cli.latest': '已經是最新版（v{version}）。',
    'update.cli.available': '有新版本：v{latest}（你目前是 v{current}）。',
    'update.cli.notes': '更新內容：',
    'update.cli.error': '檢查不了更新：{err}',
    'update.cli.confirm': '現在更新嗎？[y/N] ',
    'update.cli.cancelled': '不更新。',
    'update.cli.started': '正在背景更新，完成後小克會自動重新啟動。記錄檔：{path}',
    'update.cli.dev': "這是原始碼資料夾，請改用 'git pull' 更新。",
    'update.cli.hint': "執行 'claude-pet update' 來安裝。",
})
ZH_CN.update({
    'menu.update': '更新到 v{version}',
    'bubble.update': '有新版本：v{version}',
    'bubble.updated': '已更新到 v{version}！',
    'bubble.update_failed': '更新失败，请查看 update.log',
    'bubble.up_to_date': '已经是最新版（v{version}）',
    'bubble.update_checking': '正在检查更新…',
    'bubble.update_error': '检查不了更新',
    'bubble.update_unconfigured': '还没有设置更新来源',
    'settings.updates': '更新',
    'settings.updates_desc': '每天检查一次 GitHub，有新版本时提醒我',
    'settings.check_now': '立即检查',
    'update.status.latest': '版本 {version}・已是最新',
    'update.status.available': '版本 {current}・有新版 v{latest}',
    'update.status.checking': '检查中…',
    'update.status.error': '版本 {version}・暂时检查不了',
    'update.status.unconfigured': '版本 {version}・还没有设置更新来源',
    'update.title': '有新版本',
    'update.subtitle': 'v{current} → v{latest}',
    'update.whats_new': '更新内容',
    'update.no_notes': '（没有提供更新说明）',
    'update.now': '立即更新',
    'update.later': '以后再说',
    'update.skip': '跳过这个版本',
    'update.updating': '更新中…小克会先关闭，马上回来。',
    'update.dev': "这是源码文件夹，不会自己更新。请在文件夹里执行 'git pull'。",
    'update.cli.unconfigured': '还没有设置更新来源（尚未指定 GitHub 仓库）。',
    'update.cli.latest': '已经是最新版（v{version}）。',
    'update.cli.available': '有新版本：v{latest}（你当前是 v{current}）。',
    'update.cli.notes': '更新内容：',
    'update.cli.error': '检查不了更新：{err}',
    'update.cli.confirm': '现在更新吗？[y/N] ',
    'update.cli.cancelled': '不更新。',
    'update.cli.started': '正在后台更新，完成后小克会自动重新启动。日志文件：{path}',
    'update.cli.dev': "这是源码文件夹，请改用 'git pull' 更新。",
    'update.cli.hint': "运行 'claude-pet update' 来安装。",
})
